select
  `condition_id`,
  `additional_detail`,
  `previous_condition_id`,
  `concept_id`,
  `condition_non_coded`,
  `status`,
  `onset_date`,
  `date_created`,
  `voided`,
  `date_voided`,
  `void_reason`,
  `uuid`,
  `creator`,
  `voided_by`,
  `patient_id`,
  `end_date`
from
  conditions
  